### ISSUE TITLE
Unhandled C++ exception

### ISSUE THREAD

**Issue by 4hsc** [frifox/gw2dps#40] opened 2016-02-14 00:38 UTC
Hello,
When I try to inject the .dll, a "Unhandled C++ exception: One or more patterns not found" error comes up.

Windows 10, 64 bit gw2.exe

Thank you

**Comment by frifox** [comment] 2016-02-14 00:38
Using the latests build, 2016-02-10 one?

**Comment by 4hsc** [comment] 2016-02-14 03:41
Yes

**Comment by hairys** [comment] 2016-02-14 03:49
Is that Gw2-64.exe?

**Comment by 4hsc** [comment] 2016-02-14 04:20
Exactly

**Comment by hairys** [comment] 2016-02-14 04:23
How often does it do this to you? Try closing the game and re-opening it. Then try injecting again. Do this a few times. Does it show the error every time?
What build of the game do you have? (hit F11, bottom left corner of options panel).

**Comment by 4hsc** [comment] 2016-02-14 04:39
Build: 57,918

I tried a few times, closing the game and re-opening it, downloaded it a couple times two just to be sure I was using the latest version of gw2dps, etc...
Yes it show the error every time...

Forgot to mention that it still says that the .dll was injected successfully, just before the error, as it shows in this print screen:

http://imgur.com/oKAcRmI

Thank you

**Comment by hairys** [comment] 2016-02-14 04:42
I don't have Win10, but try running both the game and injector as admin. Works fine for me, Win7, Gw2-64.exe

**Comment by frifox** [comment] 2016-02-16 06:01
I do have Win10 and have no issues with both x86 and x64.

**Comment by hairys** [comment] 2016-02-16 19:30
The only thing I can recommend is the generic stuff frifox stated in another issue:
- Running the injector and game as Administrator
- Turning off Antivirus
- Updating all drivers & installing os updates
- Reinstalling all redist packages

**Comment by 4hsc** [comment] 2016-02-17 17:35
Still the same error :/

Well, thank you anyway

**Comment by 4hsc** [comment] 2016-02-17 21:44
Ive google that exception and I cant find anything mentioning that specific error.
Do yiu have any idea what could be causing this so i can try debugging this, if I manage to fix this ill make a push request.

**Comment by frifox** [comment] 2016-02-17 22:16
The error gets thrown from /src/hacklib/include/hacklib/PatternScanner.h, line 154:
https://bitbucket.org/rafzi/hacklib/src/06499783a8a9ca11fdf966a4d4380c30bd08f04a/src/hacklib/src/PatternScanner.cpp?at=master&fileviewer=file-view-default#PatternScanner.cpp-153

Start there and walk backwards to trace the cause.

**Comment by hairys** [comment] 2016-02-17 22:59
Some other questions that I'm curious about:
- Are you running any other client other than NA (eg. EU client, chinese client)?
- Are you running any other mods/overlays? That includes things like ShadowPlay and OBS.

**Comment by snakelayer** [comment] 2016-02-18 06:20
To add to hairys' comment, the error message suggests your local gw2 executable is not normal or has been modified. I haven't seen this suggested, but try deleting and downloading a fresh Gw2.exe.

**Comment by 4hsc** [comment] 2016-02-19 02:03
> Some other questions that I'm curious about:

    Are you running any other client other than NA (eg. EU client, chinese client)?
    Are you running any other mods/overlays? That includes things like ShadowPlay and OBS.

No and No for both questions.
First I tried restarting my computer in safe mode just in case, and tried to inject. Same error.
Then I reinstalled the game. Same thing.
I tried on my other laptop too, same error.

**Closed** 2016-04-13 17:12 UTC
